export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Blog } from './Blog'
export { default as Verify } from './Verify'
export { default as Profile } from './Profile'